In [1]:
import pandas as pd
import numpy as np

In [2]:
featureData=pd.read_csv("TemperatureDatawithCases.csv")
featureData.head(5)

Unnamed: 0        date  windspeedKmph  tempC  humidity  pressure  \
0           0  2020-02-27         16.125  2.125    87.750  1001.750   
1           1  2020-02-28         21.750  3.000    81.500  1012.000   
2           2  2020-02-29         29.250  8.000    75.500   993.875   
3           3  2020-03-01         25.500  5.750    75.875   992.500   
4           4  2020-03-02         15.375  5.375    87.250   989.875   

   HeatIndexC  precipMM      date.1  Number  
0       2.375    1.6875  2020-02-27     1.0  
1       3.250    0.4625  2020-02-28     1.0  
2       8.125    0.8000  2020-02-29     3.0  
3       5.750    0.1125  2020-03-01     5.0  
4       5.375    0.8875  2020-03-02     5.0

In [3]:
featureData.columns.values

array(['Unnamed: 0', 'date', 'windspeedKmph', 'tempC', 'humidity',
       'pressure', 'HeatIndexC', 'precipMM', 'date.1', 'Number'],
      dtype=object)

In [4]:
copy=featureData.copy

In [5]:
featureData=featureData.drop(['Unnamed: 0','date.1'], axis=1)

In [6]:
featureData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 8 columns):
date             32 non-null object
windspeedKmph    32 non-null float64
tempC            32 non-null float64
humidity         32 non-null float64
pressure         32 non-null float64
HeatIndexC       32 non-null float64
precipMM         32 non-null float64
Number           32 non-null float64
dtypes: float64(7), object(1)
memory usage: 2.1+ KB


In [7]:
type(featureData['date'][0])

str

In [8]:
featureData['date'] = pd.to_datetime(featureData['date'])

In [9]:
featureData['date'].head()
type(featureData['date'])

pandas.core.series.Series

In [10]:
#extract the month value and weekday
list_months=[]
for i in range(featureData.shape[0]):
    list_months.append(featureData['date'][i].month)
featureData['Month Value'] = list_months


In [11]:
def date_to_weekday(date_value):
    return date_value.weekday()
featureData['Day of the Week'] = featureData['date'].apply(date_to_weekday)

In [12]:
featureData.head()

date  windspeedKmph  tempC  humidity  pressure  HeatIndexC  precipMM  \
0 2020-02-27         16.125  2.125    87.750  1001.750       2.375    1.6875   
1 2020-02-28         21.750  3.000    81.500  1012.000       3.250    0.4625   
2 2020-02-29         29.250  8.000    75.500   993.875       8.125    0.8000   
3 2020-03-01         25.500  5.750    75.875   992.500       5.750    0.1125   
4 2020-03-02         15.375  5.375    87.250   989.875       5.375    0.8875   

   Number  Month Value  Day of the Week  
0     1.0            2                3  
1     1.0            2                4  
2     3.0            2                5  
3     5.0            3                6  
4     5.0            3                0

In [13]:
featureData=featureData.drop(['date'],axis=1)

In [14]:
featureData.head()

windspeedKmph  tempC  humidity  pressure  HeatIndexC  precipMM  Number  \
0         16.125  2.125    87.750  1001.750       2.375    1.6875     1.0   
1         21.750  3.000    81.500  1012.000       3.250    0.4625     1.0   
2         29.250  8.000    75.500   993.875       8.125    0.8000     3.0   
3         25.500  5.750    75.875   992.500       5.750    0.1125     5.0   
4         15.375  5.375    87.250   989.875       5.375    0.8875     5.0   

   Month Value  Day of the Week  
0            2                3  
1            2                4  
2            2                5  
3            3                6  
4            3                0

In [15]:
featureData.columns.values

array(['windspeedKmph', 'tempC', 'humidity', 'pressure', 'HeatIndexC',
       'precipMM', 'Number', 'Month Value', 'Day of the Week'],
      dtype=object)

In [16]:
columns_updt=['windspeedKmph', 'tempC', 'humidity', 'pressure', 'HeatIndexC',
       'precipMM', 'Month Value', 'Day of the Week','Number']
featureData=featureData[columns_updt]
featureData.tail()

windspeedKmph  tempC  humidity  pressure  HeatIndexC  precipMM  \
27         14.875  5.625    44.875  1027.500       5.625    0.0000   
28         19.625  5.250    54.000  1023.375       5.250    0.0000   
29         20.500  8.125    65.875  1020.875       8.125    0.0000   
30         22.125  8.375    68.500  1023.000       8.375    0.0000   
31         27.000  4.375    57.625  1029.375       4.375    0.0875   

    Month Value  Day of the Week  Number  
27            3                2  1861.0  
28            3                3  2100.0  
29            3                4  2426.0  
30            3                5  2678.0  
31            3                6  2950.0

In [17]:
data_preprocessed=featureData
data_preprocessed.head()
data_preprocessed2=data_preprocessed.copy()

In [18]:
targets2 = np.where(data_preprocessed2['Number'] > 
                   data_preprocessed2['Number'].median(), 1, 0)
targets=data_preprocessed['Number']
targets=np.array(targets)
targets

array([1.000e+00, 1.000e+00, 3.000e+00, 5.000e+00, 5.000e+00, 1.200e+01,
       1.700e+01, 2.400e+01, 3.400e+01, 5.700e+01, 9.300e+01, 1.350e+02,
       1.570e+02, 2.180e+02, 2.660e+02, 3.600e+02, 4.030e+02, 4.460e+02,
       5.540e+02, 6.340e+02, 7.280e+02, 8.420e+02, 9.710e+02, 1.139e+03,
       1.358e+03, 1.508e+03, 1.685e+03, 1.861e+03, 2.100e+03, 2.426e+03,
       2.678e+03, 2.950e+03])

In [19]:
#data_preprocessed['Number']=targets
data_preprocessed2['Number'] =targets2

In [20]:
data_with_targets = data_preprocessed.drop(['Day of the Week'],axis=1)
data_with_targets2 = data_preprocessed2.drop(['Day of the Week'],axis=1)


In [21]:
data_with_targets is data_preprocessed

False

In [22]:
data_with_targets.head()
targets

array([1.000e+00, 1.000e+00, 3.000e+00, 5.000e+00, 5.000e+00, 1.200e+01,
       1.700e+01, 2.400e+01, 3.400e+01, 5.700e+01, 9.300e+01, 1.350e+02,
       1.570e+02, 2.180e+02, 2.660e+02, 3.600e+02, 4.030e+02, 4.460e+02,
       5.540e+02, 6.340e+02, 7.280e+02, 8.420e+02, 9.710e+02, 1.139e+03,
       1.358e+03, 1.508e+03, 1.685e+03, 1.861e+03, 2.100e+03, 2.426e+03,
       2.678e+03, 2.950e+03])

In [23]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs2 = data_with_targets2.iloc[:,:-1]

In [24]:
#STANDARDIZATION
from sklearn.preprocessing import StandardScaler

weather_scaler= StandardScaler()
weather_scaler2=StandardScaler()

In [25]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [26]:
unscaled_inputs.columns.values
unscaled_inputs2.columns.values

array(['windspeedKmph', 'tempC', 'humidity', 'pressure', 'HeatIndexC',
       'precipMM', 'Month Value'], dtype=object)

In [27]:
columns_to_omit=[]
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]
columns_to_scale2 = [x for x in unscaled_inputs2.columns.values if x not in columns_to_omit]


In [28]:
weather_scaler = CustomScaler(columns_to_scale)
weather_scaler2 = CustomScaler(columns_to_scale2)

In [29]:
weather_scaler.fit(unscaled_inputs)
weather_scaler2.fit(unscaled_inputs2)

C:\Users\20195478\python\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


CustomScaler(columns=['windspeedKmph', 'tempC', 'humidity', 'pressure',
                      'HeatIndexC', 'precipMM', 'Month Value'],
             copy=None, with_mean=None, with_std=None)

In [30]:
scaled_inputs = weather_scaler.transform(unscaled_inputs)
scaled_inputs2 = weather_scaler2.transform(unscaled_inputs2)

In [31]:
scaled_inputs
scaled_inputs2

windspeedKmph     tempC  humidity  pressure  HeatIndexC  precipMM  \
0       -0.608130 -2.085009  1.168829 -1.041339   -1.980927  1.792850   
1        0.334504 -1.696455  0.695619 -0.223233   -1.596081  0.025918   
2        1.591351  0.523854  0.241337 -1.669884    0.548062  0.512726   
3        0.962928 -0.475285  0.269730 -1.779630   -0.496520 -0.478920   
4       -0.733815 -0.641808  1.130972 -1.989145   -0.661454  0.638935   
5       -0.650025 -0.808331  0.402229 -1.111177   -0.826389 -0.280591   
6       -0.922342 -0.253254  0.619905 -0.432748   -0.276608 -0.496950   
7       -0.272971 -0.364269  1.301328 -1.480323   -0.386564  1.883000   
8       -0.000655 -0.586300  1.168829 -1.610022   -0.606476  2.027239   
9       -0.985184 -0.308762  0.402229  0.076074   -0.331586 -0.623159   
10       0.879138  0.412839  0.771332 -0.233210    0.383128  0.025918   
11      -0.126339 -0.031223  0.733476 -0.283095   -0.056696 -0.316651   
12       1.675140  0.856901  1.206686 -0.722078    1.152821  2.892676   
13       0.481136  1.745024  0.979545 -0.422771    1.867535  2.009210   
14       2.240721  0.912408 -0.383300 -0.472656    0.932908  0.783175   
15       0.837243 -0.086731  0.070982  0.026189   -0.111674 -0.496950   
16      -0.964237 -0.031223  0.487406  0.375381   -0.056696 -0.551040   
17      -0.000655  1.023424  0.572584 -0.063603    0.987886 -0.605129   
18      -2.074451  1.689516  0.421157  0.265635    1.647623 -0.623159   
19      -1.173711  0.912408 -0.742940  1.053810    0.877930 -0.641189   
20      -0.922342  1.800532 -0.042589  0.924110    1.757579 -0.641189   
21      -1.990661  1.800532  0.477942  0.844295    1.757579 -0.641189   
22       0.271662  0.468346 -0.203480  0.924110    0.438106 -0.551040   
23       0.921033 -0.752824 -0.600977  1.063787   -0.771410 -0.641189   
24       0.858190 -1.030362 -1.452755  1.273302   -1.046301 -0.641189   
25      -0.021602 -1.141378 -2.134178  1.412979   -1.156257 -0.641189   
26      -0.503393 -0.808331 -2.209891  1.293256   -0.826389 -0.641189   
27      -0.817605 -0.530793 -2.077392  1.013903   -0.551498 -0.641189   
28      -0.021602 -0.697316 -1.386506  0.684665   -0.716432 -0.641189   
29       0.125030  0.579362 -0.487406  0.485127    0.548062 -0.641189   
30       0.397347  0.690377 -0.288658  0.654734    0.658018 -0.641189   
31       1.214297 -1.085870 -1.112044  1.163556   -1.101279 -0.514980   

    Month Value  
0     -3.109126  
1     -3.109126  
2     -3.109126  
3      0.321634  
4      0.321634  
5      0.321634  
6      0.321634  
7      0.321634  
8      0.321634  
9      0.321634  
10     0.321634  
11     0.321634  
12     0.321634  
13     0.321634  
14     0.321634  
15     0.321634  
16     0.321634  
17     0.321634  
18     0.321634  
19     0.321634  
20     0.321634  
21     0.321634  
22     0.321634  
23     0.321634  
24     0.321634  
25     0.321634  
26     0.321634  
27     0.321634  
28     0.321634  
29     0.321634  
30     0.321634  
31     0.321634

In [32]:
from sklearn.model_selection import train_test_split
targets

array([1.000e+00, 1.000e+00, 3.000e+00, 5.000e+00, 5.000e+00, 1.200e+01,
       1.700e+01, 2.400e+01, 3.400e+01, 5.700e+01, 9.300e+01, 1.350e+02,
       1.570e+02, 2.180e+02, 2.660e+02, 3.600e+02, 4.030e+02, 4.460e+02,
       5.540e+02, 6.340e+02, 7.280e+02, 8.420e+02, 9.710e+02, 1.139e+03,
       1.358e+03, 1.508e+03, 1.685e+03, 1.861e+03, 2.100e+03, 2.426e+03,
       2.678e+03, 2.950e+03])

In [45]:
train_test_split(unscaled_inputs, targets)

[    windspeedKmph   tempC  humidity  pressure  HeatIndexC  precipMM  \
 4          15.375   5.375    87.250   989.875       5.375    0.8875   
 13         22.625  10.750    85.250  1009.500      11.125    1.8375   
 3          25.500   5.750    75.875   992.500       5.750    0.1125   
 18          7.375  10.625    77.875  1018.125      10.625    0.0125   
 2          29.250   8.000    75.500   993.875       8.125    0.8000   
 9          13.875   6.125    77.625  1015.750       6.125    0.0125   
 28         19.625   5.250    54.000  1023.375       5.250    0.0000   
 25         19.625   4.250    44.125  1032.500       4.250    0.0000   
 26         16.750   5.000    43.125  1031.000       5.000    0.0000   
 21          7.875  10.875    78.625  1025.375      10.875    0.0000   
 20         14.250  10.875    71.750  1026.375      10.875    0.0000   
 11         19.000   6.750    82.000  1011.250       6.750    0.2250   
 30         22.125   8.375    68.500  1023.000       8.375    0.

In [55]:
x_train, x_test, y_train, y_test = train_test_split(unscaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [56]:
print (x_train.shape, y_train.shape)

(25, 7) (25,)


In [57]:
print (x_test.shape, y_test.shape)

(7, 7) (7,)


In [58]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics

# Linear Regression

In [59]:
reg=LinearRegression()

In [60]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [61]:
reg.score(x_train,y_train)

0.6918926993149765

In [62]:
reg.intercept_

-29409.799258388164

In [63]:
reg.coef_

array([   6.35943699,  657.67802303,  -28.11380795,   31.49525172,
       -639.10385365,  209.63178048,  -49.48801728])

In [64]:
featurename = unscaled_inputs.columns.values

In [65]:
summary_table = pd.DataFrame (columns=['Feature name'], data = featurename)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0  windspeedKmph     6.359437
1          tempC   657.678023
2       humidity   -28.113808
3       pressure    31.495252
4     HeatIndexC  -639.103854
5       precipMM   209.631780
6    Month Value   -49.488017

# Logistic Regression

In [66]:
train_test_split(scaled_inputs2, targets2)

[    windspeedKmph     tempC  humidity  pressure  HeatIndexC  precipMM  \
 30       0.397347  0.690377 -0.288658  0.654734    0.658018 -0.641189   
 2        1.591351  0.523854  0.241337 -1.669884    0.548062  0.512726   
 25      -0.021602 -1.141378 -2.134178  1.412979   -1.156257 -0.641189   
 21      -1.990661  1.800532  0.477942  0.844295    1.757579 -0.641189   
 7       -0.272971 -0.364269  1.301328 -1.480323   -0.386564  1.883000   
 18      -2.074451  1.689516  0.421157  0.265635    1.647623 -0.623159   
 16      -0.964237 -0.031223  0.487406  0.375381   -0.056696 -0.551040   
 3        0.962928 -0.475285  0.269730 -1.779630   -0.496520 -0.478920   
 22       0.271662  0.468346 -0.203480  0.924110    0.438106 -0.551040   
 12       1.675140  0.856901  1.206686 -0.722078    1.152821  2.892676   
 23       0.921033 -0.752824 -0.600977  1.063787   -0.771410 -0.641189   
 28      -0.021602 -0.697316 -1.386506  0.684665   -0.716432 -0.641189   
 1        0.334504 -1.696455  0.695619

In [67]:
x_train, x_test, y_train, y_test = train_test_split(unscaled_inputs2, targets2, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [73]:
from sklearn.linear_model import LogisticRegression

In [75]:
reg.fit(x_train,y_train)
reg.score(x_train,y_train)

0.7560397183435352

In [76]:
reg.intercept_

-27.793503085151205

In [77]:
reg.coef_

array([-0.00895209,  0.62760735, -0.00585961,  0.02877901, -0.5827115 ,
        0.04720521, -0.20894895])

In [78]:
featurename2 = unscaled_inputs2.columns.values

In [79]:
summary_table = pd.DataFrame (columns=['Feature name'], data = featurename2)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0  windspeedKmph    -0.008952
1          tempC     0.627607
2       humidity    -0.005860
3       pressure     0.028779
4     HeatIndexC    -0.582712
5       precipMM     0.047205
6    Month Value    -0.208949